name:                legio
version:             0.2.0.0
github:              "Sventimir/legio"
license:             BSD3
author:              "Sventimir"
maintainer:          "svantimir@gmail.com"
copyright:           "2020 Sventimir"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/legio#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - attoparsec
    - bifunctors
    - containers
    - extra
    - megaparsec
    - MonadRandom
    - mtl
    - parser-combinators
    - random-shuffle
    - text
    - transformers
    - transformers-either

executables:
  legio:
    main:                Main.hs
    source-dirs:         legio
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - attoparsec
    - containers
    - either
    - extra
    - legio
    - megaparsec
    - MonadRandom
    - mtl
    - parser-combinators
    - random
    - text
    - transformers
    - transformers-either

  exercise:
    main:               Main.hs
    source-dirs:        exercise
    dependencies:
    - legio
    - mtl

tests:
  legio-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - legio
